spring.application.name=patient-service
server.port=8081

spring.datasource.url=jdbc:postgresql://patient-db:5432/patientdb
spring.datasource.username=user
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# Désactiver complètement CORS
spring.web.cors.allow-credentials=false
spring.web.cors.allowed-origins=http://localhost:3000
spring.web.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
spring.web.cors.allowed-headers=*

# Désactiver la configuration CORS automatique
spring.web.cors.enabled=false
