# Application
spring.application.name=pharmacy-service
server.port=8087
server.address=0.0.0.0

# Database - PostgreSQL avec Docker
spring.datasource.url=jdbc:postgresql://pharmacy-db:5432/pharmacydb
spring.datasource.username=user
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Logging
logging.level.org.springframework.web=INFO
logging.level.org.hibernate=INFO